--To see all SPs in db,
-- SELECT ROUTINE_NAME, ROUTINE_SCHEMA, ROUTINE_DEFINITION
-- FROM information_schema.routines
-- WHERE Routine_Type = 'Procedure'

DELIMITER //
DROP PROCEDURE IF EXISTS sp_MYSPNAMEHERE//
CREATE PROCEDURE sp_MYSPNAMEHERE(IN MYINTEGER INT)
	BEGIN
		DECLARE i INT;

	END //
DELIMITER ;