--To See triggers in db, SHOW TRIGGERS

--INSERT, before
DELIMITER //
DROP TRIGGER IF EXISTS Table_BEFORE_INSERT_trig//
CREATE TRIGGER Table_BEFORE_INSERT_trig
BEFORE INSERT ON MYTABLENAME1
FOR EACH ROW
BEGIN
  INSERT INTO MYTABLENAME2 VALUES (NEW.id,NEW.name);
END //
DELIMITER ;

--UPDATE, after
DELIMITER //
DROP TRIGGER IF EXISTS Table_AFTER_UPDATE_trig//
CREATE TRIGGER MYTRIGGERNAME
AFTER UPDATE ON MYTABLENAME1 ON person
FOR EACH ROW
BEGIN
    UPDATE MYTABLENAME2 SET FIELD1 = 'ChangedValue' WHERE FIELD2 = 2;
END//
DELIMITER ;

--Before UPDATE, Insert to new table
DELIMITER //
DROP TRIGGER IF EXISTS Table_BEFORE_UPDATE_trig//
CREATE TRIGGER Table_BEFORE_UPDATE_trig
BEFORE UPDATE ON MYTABLENAME1
FOR EACH ROW
BEGIN
    INSERT INTO MYTABLENAME2 (Field1, Field2) VALUES (OLD.FIELD1, NEW.FIELD1);
END//
DELIMITER ;